from django.shortcuts import render
from django.http import HttpResponse
import pandas as pd
import numpy as np
from matplotlib import pyplot
import matplotlib.pyplot as plt
import csv
import matplotlib


def index(request):
	return render(request,'home.html')


def display_plot(request):
    Years=request.POST['Years']
    Years=int(Years)
    plt.clf()
    Gender=request.POST['Gender']
    Weight=request.POST['Weight']
    Weight=float(Weight)
    Height=request.POST['Height']
    Height=float(Height)
    BMI=float(Weight)/(float(Height)/100)**2


    if Years<20:
        
        Months=request.POST['Months']
        Months=int(Months)
        Age=(int(Years)*12)+int(Months)


        if (Gender=="Male" and Age<=60)  :
            Head_circumference=request.POST['Head_circumference']
            Head_circumference=int(Head_circumference)

            plt.subplot(2,2,1)
            aw = pd.read_csv('b_age_weight(0to5).csv')
            plt.plot(aw['Month'],aw['3rd'])
            plt.plot(aw['Month'],aw['5th'])
            plt.plot(aw['Month'],aw['10th'])
            plt.plot(aw['Month'],aw['25th'])
            plt.plot(aw['Month'],aw['50th'])
            plt.plot(aw['Month'],aw['75th'])
            plt.plot(aw['Month'],aw['90th'])
            plt.plot(aw['Month'],aw['95th'])
            plt.plot(aw['Month'],aw['98th'])
            plt.scatter(Age,Weight)
            plt.grid(True)
            plt.xlabel('Age in months',fontsize=8)
            plt.ylabel('Weight in kg',fontsize=8)
            plt.xticks(fontsize=8)
            plt.yticks(fontsize=8)
            plt.text(29.5,10.8,'3%', fontsize = 8)
            plt.text(32,11.4,'5%',fontsize = 8)
            plt.text(33.5,12.2,'10%',fontsize = 8)
            plt.text(35.7,13.3,'25%',fontsize = 8)
            plt.text(39,14.8,'50%',fontsize = 8)
            plt.text(42,16.5,'75%',fontsize = 8)
            plt.text(46,18.7,'90%',fontsize = 8)
            plt.text(49,20.5,'95%',fontsize = 8)
            plt.text(53,22.3,'98%',fontsize = 8)

            
            plt.subplot(2,2,2)
            al = pd.read_csv("b_age_length(0to5).csv")
            plt.plot(al['Month'], al['3rd'])
            plt.plot(al['Month'], al['5th'])
            plt.plot(al['Month'], al['10th'])
            plt.plot(al['Month'], al['25th'])
            plt.plot(al['Month'], al['50th'])
            plt.plot(al['Month'], al['75th'])
            plt.plot(al['Month'], al['90th'])
            plt.plot(al['Month'], al['95th'])
            plt.plot(al['Month'], al['98th'])
            plt.scatter(Age, Height)
            plt.grid(True)
            plt.xlabel('Age in months',fontsize=8)
            plt.ylabel('Height in cms',fontsize=8)
            plt.xticks(fontsize=8)
            plt.yticks(fontsize=8)
            plt.text(23,79.5,'3%', fontsize = 8)
            plt.text(25,82,'5%',fontsize = 8)
            plt.text(27.5,85.5,'10%',fontsize = 8)
            plt.text(30,89.5,'25%',fontsize = 8)
            plt.text(33,94,'50%',fontsize = 8)
            plt.text(36,97.5,'75%',fontsize = 8)
            plt.text(39,102,'90%',fontsize = 8)
            plt.text(44,107,'95%',fontsize = 8)
            plt.text(49,111,'98%',fontsize = 8)

            plt.subplot(2,2,3)
            ah = pd.read_csv("b_age_headc(0to5).csv")
            plt.plot(ah['Month'], ah['3rd'])
            plt.plot(ah['Month'], ah['5th'])
            plt.plot(ah['Month'], ah['10th'])
            plt.plot(ah['Month'], ah['25th'])
            plt.plot(ah['Month'], ah['50th'])
            plt.plot(ah['Month'], ah['75th'])
            plt.plot(ah['Month'], ah['90th'])
            plt.plot(ah['Month'], ah['95th'])
            plt.plot(ah['Month'], ah['97th'])
            plt.plot(ah['Month'], ah['99th'])
            plt.scatter(Age, Head_circumference)
            plt.grid(True)
            plt.xlabel('Age in months',fontsize=8)
            plt.ylabel('Head Circumference in cms',fontsize=8)
            plt.xticks(fontsize=8)
            plt.yticks(fontsize=8)
            plt.text(20,45,'3%', fontsize = 8)
            plt.text(24,45.7,'5%',fontsize = 8)
            plt.text(28,46.7,'10%',fontsize = 8)
            plt.text(31,47.8,'25%',fontsize = 8)
            plt.text(35,49,'50%',fontsize = 8)
            plt.text(39,50.5,'75%',fontsize = 8)
            plt.text(42,51.5,'90%',fontsize = 8)
            plt.text(45,52,'95%',fontsize = 8)
            plt.text(48,52.8,'97%',fontsize = 8)
            plt.text(51,53.5,'99%',fontsize = 8)

            plt.subplot(2,2,4)
            lw = pd.read_csv("b_length_weight(0to5).csv")
            plt.plot(lw['Length'], lw['3rd'])
            plt.plot(lw['Length'], lw['5th'])
            plt.plot(lw['Length'], lw['10th'])
            plt.plot(lw['Length'], lw['25th'])
            plt.plot(lw['Length'], lw['50th'])
            plt.plot(lw['Length'], lw['75th'])
            plt.plot(lw['Length'], lw['90th'])
            plt.plot(lw['Length'], lw['95th'])
            plt.plot(lw['Length'], lw['98th'])
            plt.scatter(Height, Weight)
            plt.grid(True)
            plt.xlabel('Height in cms',fontsize=8)
            plt.ylabel('Weight in kg',fontsize=8)
            plt.xticks(fontsize=8)
            plt.yticks(fontsize=8)
            plt.text(85,9.6,'3%', fontsize = 8)
            plt.text(87,10.4,'5%',fontsize = 8)
            plt.text(89,11.2,'10%',fontsize = 8)
            plt.text(91,12.2,'25%',fontsize = 8)
            plt.text(94,13.5,'50%',fontsize = 8)
            plt.text(96,14.7,'75%',fontsize = 8)
            plt.text(98,16.1,'90%',fontsize = 8)
            plt.text(101,17.6,'95%',fontsize = 8)
            plt.text(104,19.5,'98%',fontsize = 8)
            plt.savefig('chart/static/fig.png')


                

        elif (Gender=="Male" and 60<Age<240):
        
            plt.subplot(2,2,1)
            aw = pd.read_csv("b_wt_age.csv")
            plt.plot(aw['Agemos'], aw['P3'])
            plt.plot(aw['Agemos'], aw['P5'])
            plt.plot(aw['Agemos'], aw['P10'])
            plt.plot(aw['Agemos'], aw['P25'])
            plt.plot(aw['Agemos'], aw['P50'])
            plt.plot(aw['Agemos'], aw['P75'])
            plt.plot(aw['Agemos'], aw['P90'])
            plt.plot(aw['Agemos'], aw['P95'])
            plt.plot(aw['Agemos'], aw['P97'])
            plt.scatter(Age, Weight)
            plt.grid(True)
            plt.xlabel('Age in months',fontsize=8)
            plt.ylabel('Weight in kg',fontsize=8)
            plt.xticks(fontsize=8)
            plt.yticks(fontsize=8)
            plt.text(174,38.5,'3%', fontsize = 8)
            plt.text(180,42.1,'5%',fontsize =8)
            plt.text(189,48.5,'10%',fontsize = 8)
            plt.text(194,55,'25%',fontsize = 8)
            plt.text(203,64,'50%',fontsize = 8)
            plt.text(210,74,'75%',fontsize = 8)
            plt.text(216,84.5,'90%',fontsize = 8)
            plt.text(221,92.5,'95%',fontsize = 8)
            plt.text(228,98.5,'97%',fontsize = 8)

            plt.subplot(2,2,2)
            al = pd.read_csv("b_len_age.csv")
            plt.plot(al['Agemos'], al['P3'])
            plt.plot(al['Agemos'], al['P5'])
            plt.plot(al['Agemos'], al['P10'])
            plt.plot(al['Agemos'], al['P25'])
            plt.plot(al['Agemos'], al['P50'])
            plt.plot(al['Agemos'], al['P75'])
            plt.plot(al['Agemos'], al['P90'])
            plt.plot(al['Agemos'], al['P95'])
            plt.plot(al['Agemos'], al['P97'])
            plt.scatter(Age, Height)
            plt.grid(True)
            plt.xlabel('Age in months',fontsize=8)
            plt.ylabel('Height in cms',fontsize=8)
            plt.xticks(fontsize=8)
            plt.yticks(fontsize=8)
            plt.text(156,141,'3%', fontsize = 8)
            plt.text(162,146,'5%',fontsize = 8)
            plt.text(167,153,'10%',fontsize = 8)
            plt.text(174,162,'25%',fontsize = 8)
            plt.text(180,169.5,'50%',fontsize = 8)
            plt.text(186,176.5,'75%',fontsize =8)
            plt.text(192,182,'90%',fontsize = 8)
            plt.text(196,185.5,'95%',fontsize = 8)
            plt.text(204,188,'97%',fontsize = 8)

            plt.subplot(2,2,3)
            ah = pd.read_csv("b_bmi_agerev.csv")
            plt.plot(ah['Agemos'], ah['P3'])
            plt.plot(ah['Agemos'], ah['P5'])
            plt.plot(ah['Agemos'], ah['P10'])
            plt.plot(ah['Agemos'], ah['P25'])
            plt.plot(ah['Agemos'], ah['P50'])
            plt.plot(ah['Agemos'], ah['P75'])
            plt.plot(ah['Agemos'], ah['P85'])
            plt.plot(ah['Agemos'], ah['P90'])
            plt.plot(ah['Agemos'], ah['P95'])
            plt.plot(ah['Agemos'], ah['P97'])
            plt.scatter(Age, BMI)
            plt.grid(True)
            plt.xlabel('Age in months',fontsize=8)
            plt.ylabel('BMI in kg/cm2',fontsize=8)
            plt.xticks(fontsize=8)
            plt.yticks(fontsize=8)
            plt.text(156,15,'3%', fontsize = 8)
            plt.text(162,15.5,'5%',fontsize = 8)
            plt.text(167,16.4,'10%',fontsize = 8)
            plt.text(174,17.9,'25%',fontsize = 8)
            plt.text(180,19.8,'50%',fontsize = 8)
            plt.text(186,22.2,'75%',fontsize = 8)
            plt.text(192,24.2,'85%',fontsize = 8)
            plt.text(197,25.6,'90%',fontsize = 8)
            plt.text(204,28.1,'95%',fontsize = 8)
            plt.text(207,30,'97%',fontsize = 8)

            plt.savefig('chart/static/fig.png')




        elif (Gender=="Female" and Age<=60):
            Head_circumference=request.POST['Head_circumference']
            Head_circumference=int(Head_circumference)
          
            
            plt.subplot(2,2,1)
            aw = pd.read_csv("g_age_weight(0to5).csv")
            plt.plot(aw['Month'], aw['3rd'])
            plt.plot(aw['Month'], aw['5th'])
            plt.plot(aw['Month'], aw['10th'])
            plt.plot(aw['Month'], aw['25th'])
            plt.plot(aw['Month'], aw['50th'])
            plt.plot(aw['Month'], aw['75th'])
            plt.plot(aw['Month'], aw['90th'])
            plt.plot(aw['Month'], aw['95th'])
            plt.plot(aw['Month'], aw['98th'])
            plt.scatter(Age, Weight)
            plt.grid(True)
            plt.xlabel('Age in months',fontsize=8)
            plt.ylabel('Weight in kg',fontsize=8)
            plt.xticks(fontsize=8)
            plt.yticks(fontsize=8)
            plt.text(29.5,10.54,'3%', fontsize =8)
            plt.text(32,11,'5%',fontsize =8)
            plt.text(33.5,11.7,'10%',fontsize = 8)
            plt.text(35.7,12.7,'25%',fontsize =8)
            plt.text(39,14.2,'50%',fontsize =8)
            plt.text(42,16.2,'75%',fontsize = 8)
            plt.text(46,18.7,'90%',fontsize = 8)
            plt.text(49,20.5,'95%',fontsize = 8)
            plt.text(53,22.7,'98%',fontsize = 8)

            plt.subplot(2,2,2)
            al = pd.read_csv("g_age_length(0to5).csv")
            plt.plot(al['Month'], al['3rd'])
            plt.plot(al['Month'], al['5th'])
            plt.plot(al['Month'], al['10th'])
            plt.plot(al['Month'], al['25th'])
            plt.plot(al['Month'], al['50th'])
            plt.plot(al['Month'], al['75th'])
            plt.plot(al['Month'], al['90th'])
            plt.plot(al['Month'], al['95th'])
            plt.plot(al['Month'], al['98th'])
            plt.scatter(Age, Height)
            plt.grid(True)
            plt.xlabel('Age in months',fontsize=8)
            plt.ylabel('Height in cms',fontsize=8)
            plt.xticks(fontsize=8)
            plt.yticks(fontsize=8)
            plt.text(23,78,'3%', fontsize = 8)
            plt.text(25,81,'5%',fontsize = 8)
            plt.text(27.5,84.5,'10%',fontsize = 8)
            plt.text(30,88.5,'25%',fontsize = 8)
            plt.text(33,93,'50%',fontsize = 8)
            plt.text(36,96.9,'75%',fontsize = 8)
            plt.text(39,101,'90%',fontsize = 8)
            plt.text(44,106,'95%',fontsize = 8)
            plt.text(49,110,'98%',fontsize = 8)

            plt.subplot(2,2,3)
            ah = pd.read_csv("g_age_headc(0to5).csv")
            plt.plot(ah['Month'], ah['3rd'])
            plt.plot(ah['Month'], ah['5th'])
            plt.plot(ah['Month'], ah['10th'])
            plt.plot(ah['Month'], ah['25th'])
            plt.plot(ah['Month'], ah['50th'])
            plt.plot(ah['Month'], ah['75th'])
            plt.plot(ah['Month'], ah['90th'])
            plt.plot(ah['Month'], ah['95th'])
            plt.plot(ah['Month'], ah['97th'])
            plt.plot(ah['Month'], ah['99th'])
            plt.scatter(Age, Head_circumference)
            plt.grid(True)
            plt.xlabel('Age in months',fontsize=8)
            plt.ylabel('Head Circumference in cms',fontsize=8)
            plt.xticks(fontsize=8)
            plt.yticks(fontsize=8)
            plt.text(20,43.8,'3%', fontsize = 8)
            plt.text(24,44.6,'5%',fontsize = 8)
            plt.text(28,45.7,'10%',fontsize = 8)
            plt.text(31,47,'25%',fontsize = 8)
            plt.text(35,48,'50%',fontsize = 8)
            plt.text(39,49.5,'75%',fontsize = 8)
            plt.text(42,50.7,'90%',fontsize = 8)
            plt.text(45,51.4,'95%',fontsize = 8)
            plt.text(48.4,51.8,'97%',fontsize = 8)
            plt.text(53,52.7,'99%',fontsize = 8)


            plt.subplot(2,2,4)
            lw = pd.read_csv("g_length_weight(0to5).csv")
            plt.plot(lw['Length'], lw['3rd'])
            plt.plot(lw['Length'], lw['5th'])
            plt.plot(lw['Length'], lw['10th'])
            plt.plot(lw['Length'], lw['25th'])
            plt.plot(lw['Length'], lw['50th'])
            plt.plot(lw['Length'], lw['75th'])
            plt.plot(lw['Length'], lw['90th'])
            plt.plot(lw['Length'], lw['95th'])
            plt.plot(lw['Length'], lw['98th'])
            plt.scatter(Height, Weight)
            plt.grid(True)
            plt.xlabel('Height in cms',fontsize=8)
            plt.ylabel('Weight in kg',fontsize=8)
            plt.xticks(fontsize=8)
            plt.yticks(fontsize=8) 
            plt.text(85,9.4,'3%', fontsize = 8)
            plt.text(87,10.1,'5%',fontsize = 8)
            plt.text(89,10.9,'10%',fontsize = 8)
            plt.text(91,12,'25%',fontsize = 8)
            plt.text(94,13.4,'50%',fontsize = 8)
            plt.text(96,14.8,'75%',fontsize = 8)
            plt.text(98,16.2,'90%',fontsize = 8)
            plt.text(101,17.8,'95%',fontsize = 8)
            plt.text(104,19.6,'98%',fontsize = 8)

            plt.savefig('chart/static/fig.png')

        elif (Gender=="Female" and 60<Age<240):
           
            plt.subplot(2,2,1)
            aw = pd.read_csv("g_wt_age.csv")
            plt.plot(aw['Agemos'], aw['P3'])
            plt.plot(aw['Agemos'], aw['P5'])
            plt.plot(aw['Agemos'], aw['P10'])
            plt.plot(aw['Agemos'], aw['P25'])
            plt.plot(aw['Agemos'], aw['P50'])
            plt.plot(aw['Agemos'], aw['P75'])
            plt.plot(aw['Agemos'], aw['P90'])
            plt.plot(aw['Agemos'], aw['P95'])
            plt.plot(aw['Agemos'], aw['P97'])
            plt.scatter(Age, Weight)
            plt.grid(True)
            plt.xlabel('Age in months',fontsize=8)
            plt.ylabel('Weight in kg',fontsize=8)
            plt.xticks(fontsize=8)
            plt.yticks(fontsize=8)
            plt.text(174,37.9,'3%', fontsize = 8)
            plt.text(180,40,'5%',fontsize = 8)
            plt.text(189,44,'10%',fontsize = 8)
            plt.text(194,48.4,'25%',fontsize = 8)
            plt.text(203,54.5,'50%',fontsize = 8)
            plt.text(210,62.5,'75%',fontsize = 8)
            plt.text(216,72.5,'90%',fontsize = 8)
            plt.text(221,81,'95%',fontsize = 8)
            plt.text(228,88,'97%',fontsize = 8)

            plt.subplot(2,2,2)
            al = pd.read_csv("g_len_age.csv")
            plt.plot(al['Agemos'], al['P3'])
            plt.plot(al['Agemos'], al['P5'])
            plt.plot(al['Agemos'], al['P10'])
            plt.plot(al['Agemos'], al['P25'])
            plt.plot(al['Agemos'], al['P50'])
            plt.plot(al['Agemos'], al['P75'])
            plt.plot(al['Agemos'], al['P90'])
            plt.plot(al['Agemos'], al['P95'])
            plt.plot(al['Agemos'], al['P97'])
            plt.scatter(Age, Height)
            plt.grid(True)
            plt.xlabel('Age in months',fontsize=8)
            plt.ylabel('Height in cms',fontsize=8)
            plt.xticks(fontsize=8)
            plt.yticks(fontsize=8)
            plt.text(156,144,'3%', fontsize = 8)
            plt.text(162,148,'5%',fontsize = 8)
            plt.text(167,151.5,'10%',fontsize = 8)
            plt.text(174,156,'25%',fontsize = 8)
            plt.text(180,161,'50%',fontsize = 8)
            plt.text(186,166,'75%',fontsize = 8)
            plt.text(192,170,'90%',fontsize = 8)
            plt.text(197,172.5,'95%',fontsize = 8)
            plt.text(204,174.5,'97%',fontsize = 8)

            plt.subplot(2,2,3)
            ah = pd.read_csv("g_bmi_agerev.csv")
            plt.plot(ah['Agemos'], ah['P3'])
            plt.plot(ah['Agemos'], ah['P5'])
            plt.plot(ah['Agemos'], ah['P10'])
            plt.plot(ah['Agemos'], ah['P25'])
            plt.plot(ah['Agemos'], ah['P50'])
            plt.plot(ah['Agemos'], ah['P75'])
            plt.plot(ah['Agemos'], ah['P85'])
            plt.plot(ah['Agemos'], ah['P90'])
            plt.plot(ah['Agemos'], ah['P95'])
            plt.plot(ah['Agemos'], ah['P97'])
            plt.scatter(Age, BMI)
            plt.grid(True)
            plt.xlabel('Age in months',fontsize=8)
            plt.ylabel('BMI in kg/cm2',fontsize=8)
            plt.xticks(fontsize=8)
            plt.yticks(fontsize=8)
            plt.text(156,14.8,'3%', fontsize = 8)
            plt.text(162,15.4,'5%',fontsize = 8)
            plt.text(167,16.2,'10%',fontsize = 8)
            plt.text(174,17.8,'25%',fontsize = 8)
            plt.text(180,19.8,'50%',fontsize = 8)
            plt.text(186,22.4,'75%',fontsize = 8)
            plt.text(192,24.4,'85%',fontsize = 8)
            plt.text(197,26.2,'90%',fontsize = 8)
            plt.text(204,29.5,'95%',fontsize = 8)
            plt.text(207,32.3,'97%',fontsize = 8)
            plt.savefig('chart/static/fig.png')

    else:

        if Gender=="Male" and Years==20 :
            
            Age=(Years*12)

            plt.subplot(2,2,1)
            aw = pd.read_csv("b_wt_age.csv")
            plt.plot(aw['Agemos'], aw['P3'])
            plt.plot(aw['Agemos'], aw['P5'])
            plt.plot(aw['Agemos'], aw['P10'])
            plt.plot(aw['Agemos'], aw['P25'])
            plt.plot(aw['Agemos'], aw['P50'])

            plt.plot(aw['Agemos'], aw['P75'])
            plt.plot(aw['Agemos'], aw['P90'])
            plt.plot(aw['Agemos'], aw['P95'])
            plt.plot(aw['Agemos'], aw['P97'])
            plt.scatter(Age, Weight)
            plt.grid(True)
            plt.xlabel('Age in months',fontsize=8)
            plt.ylabel('Weight in kg',fontsize=8)
            plt.xticks(fontsize=8)
            plt.yticks(fontsize=8)
            plt.text(174,38.5,'3%', fontsize = 8)
            plt.text(180,42.1,'5%',fontsize =8)
            plt.text(189,48.5,'10%',fontsize = 8)
            plt.text(194,55,'25%',fontsize = 8)
            plt.text(203,64,'50%',fontsize = 8)
            plt.text(210,74,'75%',fontsize = 8)
            plt.text(216,84.5,'90%',fontsize = 8)
            plt.text(221,92.5,'95%',fontsize = 8)
            plt.text(228,98.5,'97%',fontsize = 8)

            plt.subplot(2,2,2)
            al = pd.read_csv("b_len_age.csv")
            plt.plot(al['Agemos'], al['P3'])
            plt.plot(al['Agemos'], al['P5'])
            plt.plot(al['Agemos'], al['P10'])
            plt.plot(al['Agemos'], al['P25'])
            plt.plot(al['Agemos'], al['P50'])
            plt.plot(al['Agemos'], al['P75'])
            plt.plot(al['Agemos'], al['P90'])
            plt.plot(al['Agemos'], al['P95'])
            plt.plot(al['Agemos'], al['P97'])
            plt.scatter(Age, Height)
            plt.grid(True)
            plt.xlabel('Age in months',fontsize=8)
            plt.ylabel('Height in cms',fontsize=8)
            plt.xticks(fontsize=8)
            plt.yticks(fontsize=8)
            plt.text(156,141,'3%', fontsize = 8)
            plt.text(162,146,'5%',fontsize = 8)
            plt.text(167,153,'10%',fontsize = 8)
            plt.text(174,162,'25%',fontsize = 8)
            plt.text(180,169.5,'50%',fontsize = 8)
            plt.text(186,176.5,'75%',fontsize =8)
            plt.text(192,182,'90%',fontsize = 8)
            plt.text(196,185.5,'95%',fontsize = 8)
            plt.text(204,188,'97%',fontsize = 8)

            plt.subplot(2,2,3)
            ah = pd.read_csv("b_bmi_agerev.csv")
            plt.plot(ah['Agemos'], ah['P3'])
            plt.plot(ah['Agemos'], ah['P5'])
            plt.plot(ah['Agemos'], ah['P10'])
            plt.plot(ah['Agemos'], ah['P25'])
            plt.plot(ah['Agemos'], ah['P50'])
            plt.plot(ah['Agemos'], ah['P75'])
            plt.plot(ah['Agemos'], ah['P85'])
            plt.plot(ah['Agemos'], ah['P90'])
            plt.plot(ah['Agemos'], ah['P95'])
            plt.plot(ah['Agemos'], ah['P97'])
            plt.scatter(Age, BMI)
            plt.grid(True)
            plt.xlabel('Age in months',fontsize=8)
            plt.ylabel('BMI in kg/cm2',fontsize=8)
            plt.xticks(fontsize=8)
            plt.yticks(fontsize=8)
            plt.text(156,15,'3%', fontsize = 8)
            plt.text(162,15.5,'5%',fontsize = 8)
            plt.text(167,16.4,'10%',fontsize = 8)
            plt.text(174,17.9,'25%',fontsize = 8)
            plt.text(180,19.8,'50%',fontsize = 8)
            plt.text(186,22.2,'75%',fontsize = 8)
            plt.text(192,24.2,'85%',fontsize = 8)
            plt.text(197,25.6,'90%',fontsize = 8)
            plt.text(204,28.1,'95%',fontsize = 8)
            plt.text(207,30,'97%',fontsize = 8)

            plt.savefig('chart/static/fig.png')




        elif Gender=="Female" and Years==20 :
           
            Age=Years*12

            plt.subplot(2,2,1)
            aw = pd.read_csv("g_wt_age.csv")
            plt.plot(aw['Agemos'], aw['P3'])
            plt.plot(aw['Agemos'], aw['P5'])
            plt.plot(aw['Agemos'], aw['P10'])
            plt.plot(aw['Agemos'], aw['P25'])
            plt.plot(aw['Agemos'], aw['P50'])
            plt.plot(aw['Agemos'], aw['P75'])
            plt.plot(aw['Agemos'], aw['P90'])
            plt.plot(aw['Agemos'], aw['P95'])
            plt.plot(aw['Agemos'], aw['P97'])
            plt.scatter(Age, Weight)
            plt.grid(True)
            plt.xlabel('Age in months',fontsize=8)
            plt.ylabel('Weight in kg',fontsize=8)
            plt.xticks(fontsize=8)
            plt.yticks(fontsize=8)
            plt.text(174,37.9,'3%', fontsize = 8)
            plt.text(180,40,'5%',fontsize = 8)
            plt.text(189,44,'10%',fontsize = 8)
            plt.text(194,48.4,'25%',fontsize = 8)
            plt.text(203,54.5,'50%',fontsize = 8)
            plt.text(210,62.5,'75%',fontsize = 8)
            plt.text(216,72.5,'90%',fontsize = 8)
            plt.text(221,81,'95%',fontsize = 8)
            plt.text(228,88,'97%',fontsize = 8)

            plt.subplot(2,2,2)
            al = pd.read_csv("g_len_age.csv")
            plt.plot(al['Agemos'], al['P3'])
            plt.plot(al['Agemos'], al['P5'])
            plt.plot(al['Agemos'], al['P10'])
            plt.plot(al['Agemos'], al['P25'])
            plt.plot(al['Agemos'], al['P50'])
            plt.plot(al['Agemos'], al['P75'])
            plt.plot(al['Agemos'], al['P90'])
            plt.plot(al['Agemos'], al['P95'])
            plt.plot(al['Agemos'], al['P97'])
            plt.scatter(Age, Height)
            plt.grid(True)
            plt.xlabel('Age in months',fontsize=8)
            plt.ylabel('Height in cms',fontsize=8)
            plt.xticks(fontsize=8)
            plt.yticks(fontsize=8)
            plt.text(156,144,'3%', fontsize = 8)
            plt.text(162,148,'5%',fontsize = 8)
            plt.text(167,151.5,'10%',fontsize = 8)
            plt.text(174,156,'25%',fontsize = 8)
            plt.text(180,161,'50%',fontsize = 8)
            plt.text(186,166,'75%',fontsize = 8)
            plt.text(192,170,'90%',fontsize = 8)
            plt.text(197,172.5,'95%',fontsize = 8)
            plt.text(204,174.5,'97%',fontsize = 8)

            plt.subplot(2,2,3)
            ah = pd.read_csv("g_bmi_agerev.csv")
            plt.plot(ah['Agemos'], ah['P3'])
            plt.plot(ah['Agemos'], ah['P5'])
            plt.plot(ah['Agemos'], ah['P10'])
            plt.plot(ah['Agemos'], ah['P25'])
            plt.plot(ah['Agemos'], ah['P50'])
            plt.plot(ah['Agemos'], ah['P75'])
            plt.plot(ah['Agemos'], ah['P85'])
            plt.plot(ah['Agemos'], ah['P90'])
            plt.plot(ah['Agemos'], ah['P95'])
            plt.plot(ah['Agemos'], ah['P97'])
            plt.scatter(Age, BMI)
            plt.grid(True)
            plt.xlabel('Age in months',fontsize=8)
            plt.ylabel('BMI in kg/cm2',fontsize=8)
            plt.xticks(fontsize=8)
            plt.yticks(fontsize=8)
            plt.text(156,14.8,'3%', fontsize = 8)
            plt.text(162,15.4,'5%',fontsize = 8)
            plt.text(167,16.2,'10%',fontsize = 8)
            plt.text(174,17.8,'25%',fontsize = 8)
            plt.text(180,19.8,'50%',fontsize = 8)
            plt.text(186,22.4,'75%',fontsize = 8)
            plt.text(192,24.4,'85%',fontsize = 8)
            plt.text(197,26.2,'90%',fontsize = 8)
            plt.text(204,29.5,'95%',fontsize = 8)
            plt.text(207,32.3,'97%',fontsize = 8)
            plt.savefig('chart/static/fig.png')


    return render(request, 'display_plot.html')





